pipeline {
    agent any

    environment {
        AWS_ROLE_ARN = 'arn:aws:iam::640565834670:role/JenkinsTerraform'
        AWS_DEFAULT_REGION = "us-east-1"
    }

    stages {
        stage('Terraform Deploy') {
            steps {
                // Bind the OIDC token string to AWS_OIDC_TOKEN variable
                withCredentials([string(credentialsId: 'aws-oidc-token', variable: 'AWS_OIDC_TOKEN')]) {
                    sh '''
                        # Save the token string to a temporary file
                        export AWS_WEB_IDENTITY_TOKEN_FILE="$WORKSPACE_TMP/jwt_token"
                        echo "$AWS_OIDC_TOKEN" > "$AWS_WEB_IDENTITY_TOKEN_FILE"

                        # Verify AWS identity keylessly
                        // aws sts get-caller-identity

                        # Run Terraform
                        terraform init
                        terraform apply -auto-approve
                    '''
                }
            }
        } // <--- Missing closing brace for "Terraform Deploy" stage was added here

        stage('Build') {
            steps {
                sh 'echo building....'
            }
        }

        stage('Test') {
            steps {
                sh 'echo testing'
            }
        }
    }
}