# A project that you are working on has a requirement for persistent data to be available.

# Create a file on node sk8s-node-0 at index.html with the content Acct=Finance
# Create a PersistentVolume named task-pv-volume using hostPath and allocate 1Gi to it, specifying that the volume is at /opt/KDSP00101/data on the cluster's node. The configuration should specify the access mode of ReadWriteOnce - It should define the StorageClass name exam for the PersistentVolume, which will be used to bind PersistentVolumeClaim requests to this PersistentVolume.
# Create a PersistentVolumeClaim named task-pv-claim that requests a volume of at least 100Mi and specifies an access mode of ReadWriteOnce
# Create a pod that uses the PersistentVolumeClaim as a volume with a label app: my-storage-app mounting the resulting volume to a mountPath /usr/share/nginx/html inside the pod

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ask-pv-volume 
spec:
  storageClassName: storage
  claimRef:
    name: task-pv-volume
  capacity:
    storage: 1Gi
  hostPath: 
    path: /opt/KDSP00101/data 
    type: Directory
  accessMode:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
    app: my-storage-app
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  volumeMounts:
    - mouthPath: /usr/share/nginx/html
      name: mypd
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: task-pv-claim
status: {}