# A web application requires a specific version of redis to be used as a cache.

# Create a pod with the following characteristics, and leave it running when complete:

#     The pod must run in the web namespace.
#     The namespace has already been created
#     The name of the pod should be cache.
#     Use the lfccncf/redis image with the 3.2 tag
#     Expose port 6379


apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: web

---
apiVersion: v1
kind: Pod
metadata:
  name: cache
  namespace: web
spec:
  containers:
  - image: lfccncf/redis:3.2
    name: redis
    ports:
    - containerPort: 6379
