# Create a new deployment for running.nginx with the following parameters;

# Create a namespace, the name is kdpd00201.
# Run the deployment in the kdpd00201 namespace.
# Name the deployment frontend and configure with 4 replicas
# Configure the pod with a container image of lfccncf/nginx:1.13.7
# Set an environment variable of NGINX_PORT=8080 and also expose that port for the container above.

apiVersion: v1
kind: Namespace
metadata:
  name: kdpd00201
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: lfccncf-nginx
        image: lfccncf/nginx:1.13.7
        env:
        - name: NGINX_PORT 
          value: "8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
