
# Create a YAML formatted pod manifest pod.yml to create a pod named app1 that runs a container named app1cont using image ifccncf/arg-output with these command line arguments: -lines 56 -F
# Create the pod with the kubectl command using the YAML file created in the previous step
# When the pod is running display summary data about the pod in JSON format using the kubectl command and redirect the output to a file named out1.json
# All of the files you need to work with have been created, empty, for your convenience


apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app1
  name: app1
spec:
  containers:
  - image: ifccncf/arg-output
    name: app1cont
    args: ["-lines", "56", "-F"]
    
# k get pod app1 -o json > out1.json