You sometimes need to observe a pod's logs and write those logs to a file for further analysis.

Deploy the counter pod to the cluster using the provided YAML spec file at counter.yaml
Retrieve all currently available application logs from the running pod and store them in the file log_Output.txt, which has already been created

apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
  - name: busybox
    image: busybox
    args: [/bin/sh, -c ,'while true; do echo $(date); sleep 1; done']


kubectl logs counter > log_Output.txt