apiVersion: v1
kind: ResourceQuota 
metadata:
  namespace: flask-app
  name: flask-app-quota
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: "1Gi"
    limits.cpu: "3"
    limits.memory: "2Gi"