apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: secure-app
spec:
  selector:
    app: flask
    # version: stable
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: web
  type: LoadBalancer
