kind: Service
apiVersion: v1
metadata:
  name: "auth"
spec:
  selector:
    app: "auth"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: registry.k8s.io/fluentd-elasticsearch:1.20
        name: fluentd-elasticsearch

---
apiVersion: v1
kind: Pod
metadata:
  name: api-access-pod
  namespace: default
  labels:
    name: api-access-pod
spec:
  serviceAccountName: custom-service-account
  containers:
  - name: kubectl-container
    image: bitnami/kubectl:latest
    command:
      - /bin/sh
      - -c
      - "while true; do kubectl get pods; sleep 10; done"
